"""Generates a claim-pack PDF (fpdf2) for a single claim: institution
details, checklist, and claim facts. Section 8.2 `POST /claims/{id}/pack`.
"""
from __future__ import annotations

import io
from typing import Any

from app.core.logging import get_logger

logger = get_logger(__name__)


def build_claim_pack_pdf(*, claim: dict[str, Any], asset: dict[str, Any], institution: dict[str, Any] | None, checklist: list[dict[str, Any]]) -> bytes:
    from fpdf import FPDF

    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(0, 46, 110)  # brand navy
    pdf.cell(0, 12, "Paytm Virasat -- Claim Pack", ln=True)

    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(20, 20, 20)
    pdf.ln(2)
    pdf.cell(0, 8, f"Asset: {asset.get('label', '-')}", ln=True)
    pdf.cell(0, 8, f"Institution: {(institution or {}).get('name', asset.get('institution_id', '-'))}", ln=True)
    pdf.cell(0, 8, f"Claim status: {claim.get('status', 'not_started')}", ln=True)
    if claim.get("priority_score") is not None:
        pdf.cell(0, 8, f"Priority score: {claim.get('priority_score')}", ln=True)
    if institution:
        pdf.cell(0, 8, f"Claim email: {institution.get('claim_email', '-')}", ln=True)
        pdf.cell(0, 8, f"SLA (days): {institution.get('sla_days', '-')}", ln=True)

    pdf.ln(6)
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(0, 46, 110)
    pdf.cell(0, 10, "Document checklist", ln=True)
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(20, 20, 20)
    for item in checklist:
        mark = "[x]" if item.get("present") else "[ ]"
        pdf.cell(0, 8, f"{mark} {item.get('name')}", ln=True)

    pdf.ln(6)
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(90, 100, 120)
    pdf.multi_cell(
        0,
        6,
        "Virasat is not a will. A nominee may hold assets as a trustee for legal heirs; "
        "succession law still applies. Generated by Paytm Virasat's Claim Co-pilot.",
    )

    out = pdf.output()
    return bytes(out)
